---
- name: Setup Mac
  hosts: all

  vars_files:
    - config.yml
  
  roles:
    - role: elliotweiser.osx-command-line-tools
    - role: geerlingguy.mac.homebrew
      when: configure_apps
      tags: ['homebrew']
    - role: geerlingguy.mac.dock
      when: configure_dock
      tags: ['dock']

  tasks:
    - ansible.builtin.include_tasks: tasks/osx.yml
      when: configure_osx
      tags: ['osx']

  handlers:
    - name: Restart dock service
      ansible.builtin.shell: killall Dock
      listen: restart dock